version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REACT_APP_OLLAMA_URL=http://ollama:11434
      - REACT_APP_SERVER_URL=http://server:5001
    depends_on:
      - ollama
      - server
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - web-only
      - full

  server:
    build: ./server
    ports:
      - "5001:5001"
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - full

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    profiles:
      - full

volumes:
  ollama:
